create schema if not exists progressive_overload;

grant usage on schema progressive_overload to authenticated, service_role;

create table progressive_overload.user_settings (
    user_id uuid primary key references auth.users(id) on delete cascade,
    settings jsonb not null default '{}'::jsonb
        check (jsonb_typeof(settings) = 'object'),
    source_checksum text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table progressive_overload.exercises (
    user_id uuid not null references auth.users(id) on delete cascade,
    id text not null,
    name text not null check (btrim(name) <> ''),
    equipment_type text not null check (btrim(equipment_type) <> ''),
    muscle text not null check (btrim(muscle) <> ''),
    requires_weight boolean not null,
    last_sets jsonb check (
        last_sets is null or jsonb_typeof(last_sets) = 'array'
    ),
    last_date date,
    extra_fields jsonb not null default '{}'::jsonb
        check (jsonb_typeof(extra_fields) = 'object'),
    source_checksum text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    primary key (user_id, id)
);

create unique index exercises_user_name_unique
    on progressive_overload.exercises (user_id, lower(name));

create table progressive_overload.workouts (
    user_id uuid not null references auth.users(id) on delete cascade,
    id text not null,
    exercise_id text not null,
    workout_date date not null,
    reps integer not null check (reps > 0),
    weight numeric check (weight is null or weight >= 0),
    sequence integer not null check (sequence > 0),
    session_id text,
    planned_set_id text,
    superset_group_id text,
    superset_round integer check (superset_round is null or superset_round > 0),
    source text,
    superset_exercises jsonb check (
        superset_exercises is null or jsonb_typeof(superset_exercises) = 'array'
    ),
    extra_fields jsonb not null default '{}'::jsonb
        check (jsonb_typeof(extra_fields) = 'object'),
    source_checksum text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    primary key (user_id, id),
    foreign key (user_id, exercise_id)
        references progressive_overload.exercises(user_id, id)
        on update cascade on delete restrict
);

create index workouts_user_date_sequence_idx
    on progressive_overload.workouts (user_id, workout_date, sequence, id);
create index workouts_user_exercise_date_idx
    on progressive_overload.workouts (user_id, exercise_id, workout_date desc);
create index workouts_user_session_idx
    on progressive_overload.workouts (user_id, session_id)
    where session_id is not null;
create index workouts_user_superset_idx
    on progressive_overload.workouts (user_id, superset_group_id)
    where superset_group_id is not null;

create table progressive_overload.session_templates (
    user_id uuid not null references auth.users(id) on delete cascade,
    id text not null,
    name text not null check (btrim(name) <> ''),
    rows jsonb not null default '[]'::jsonb check (jsonb_typeof(rows) = 'array'),
    extra_fields jsonb not null default '{}'::jsonb
        check (jsonb_typeof(extra_fields) = 'object'),
    source_checksum text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    primary key (user_id, id)
);

create unique index session_templates_user_name_unique
    on progressive_overload.session_templates (user_id, lower(name));

create table progressive_overload.sync_runs (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    direction text not null check (
        direction in ('github_to_supabase', 'supabase_to_github')
    ),
    status text not null check (
        status in ('running', 'completed', 'failed')
    ),
    dry_run boolean not null default false,
    source text not null,
    summary jsonb not null default '{}'::jsonb,
    error_message text,
    started_at timestamptz not null default now(),
    finished_at timestamptz,
    check (
        (status = 'running' and finished_at is null) or
        (status <> 'running' and finished_at is not null)
    )
);

create index sync_runs_user_started_idx
    on progressive_overload.sync_runs (user_id, started_at desc);

create function progressive_overload.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create trigger user_settings_set_updated_at
before update on progressive_overload.user_settings
for each row execute function progressive_overload.set_updated_at();

create trigger exercises_set_updated_at
before update on progressive_overload.exercises
for each row execute function progressive_overload.set_updated_at();

create trigger workouts_set_updated_at
before update on progressive_overload.workouts
for each row execute function progressive_overload.set_updated_at();

create trigger session_templates_set_updated_at
before update on progressive_overload.session_templates
for each row execute function progressive_overload.set_updated_at();

alter table progressive_overload.user_settings enable row level security;
alter table progressive_overload.exercises enable row level security;
alter table progressive_overload.workouts enable row level security;
alter table progressive_overload.session_templates enable row level security;
alter table progressive_overload.sync_runs enable row level security;

create policy user_settings_owner
on progressive_overload.user_settings
for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy exercises_owner
on progressive_overload.exercises
for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy workouts_owner
on progressive_overload.workouts
for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy session_templates_owner
on progressive_overload.session_templates
for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy sync_runs_owner_read
on progressive_overload.sync_runs
for select to authenticated
using ((select auth.uid()) = user_id);

grant select, insert, update, delete
on all tables in schema progressive_overload
to authenticated, service_role;
grant usage, select
on all sequences in schema progressive_overload
to authenticated, service_role;

alter default privileges in schema progressive_overload
grant select, insert, update, delete on tables
to authenticated, service_role;
alter default privileges in schema progressive_overload
grant usage, select on sequences
to authenticated, service_role;

create function progressive_overload.initialize_default_exercises(target_user_id uuid)
returns void
language sql
security definer
set search_path = ''
as $$
    insert into progressive_overload.exercises (
        user_id,
        id,
        name,
        equipment_type,
        muscle,
        requires_weight
    )
    values
        (target_user_id, 'default-bench-press', 'Bench Press', 'barbell', 'chest', true),
        (target_user_id, 'default-squat', 'Squat', 'barbell', 'legs', true),
        (target_user_id, 'default-deadlift', 'Deadlift', 'barbell', 'legs', true),
        (target_user_id, 'default-pull-ups', 'Pull-ups', 'bodyweight', 'back', false),
        (target_user_id, 'default-overhead-press', 'Overhead Press', 'barbell', 'shoulders', true),
        (target_user_id, 'default-barbell-rows', 'Barbell Rows', 'barbell', 'back', true),
        (target_user_id, 'default-dips', 'Dips', 'bodyweight', 'triceps', false),
        (target_user_id, 'default-bicep-curls', 'Bicep Curls', 'dumbbell', 'biceps', true)
    on conflict do nothing;
$$;

revoke all on function progressive_overload.initialize_default_exercises(uuid)
from public, anon, authenticated;
grant execute on function progressive_overload.initialize_default_exercises(uuid)
to service_role;

create function progressive_overload.initialize_user_data()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    current_user_id uuid := auth.uid();
    initialized_user boolean;
begin
    if current_user_id is null then
        raise exception 'Authentication required';
    end if;
    insert into progressive_overload.user_settings (user_id)
    values (current_user_id)
    on conflict (user_id) do nothing
    returning true into initialized_user;
    if initialized_user then
        perform progressive_overload.initialize_default_exercises(current_user_id);
    end if;
end;
$$;

revoke all on function progressive_overload.initialize_user_data()
from public, anon;
grant execute on function progressive_overload.initialize_user_data()
to authenticated, service_role;
